config/routes.rb
Rails.application.routes.draw do
  get 'time/index'
  # 会員用
# URL /customers/sign_in ...
devise_for :users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
#ゲストユーザー
devise_scope :user do
  post 'users_guest_sign_in', to: 'public/sessions#guest_sign_in'
end

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  ########### 会員側のルーティング設定 ##########
  scope module: :public do
    root to: "homes#top"
    get '/home/about' => 'homes#about', as: 'about'
    resources :users, only: [:show, :edit, :destroy, :update, :create] do
      resource :follows, only: [:create, :destroy]
      get 'followings' => 'follows#followings', as: 'followings'
      get 'followers' => 'follows#followers', as: 'followers'
    end

    resources :posts, only: [:new, :create, :index, :show, :destroy] do
      resource :favorites, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
    end
    get "search" => "searches#search"
    get 'chat/:id', to: 'chats#show', as: 'chat'
    resources :chats, only: [:create]
    resources :notifications, only: [:index] do
      collection do
        delete 'destroy_all'
      end
    end
    resources :times, only: [:index]
  end

  ########## 管理者側のルーティング設定 ##########
  namespace :admin do
    resources :users, only: [:index, :show, :edit, :destroy, :update]
    resources :posts, only: [:new, :create, :index, :show, :destroy] do
      resources :post_comments, only: [:create, :destroy]
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates :body,presence:true,length:{maximum:200}
  has_many :post_comments, dependent: :destroy
  has_one_attached :image
  has_many :favorites, dependent: :destroy
  has_many :notifications, dependent: :destroy

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  def self.looks(search, word)
    if search == "perfect_match"
      @post = Post.where("body LIKE?","#{word}")
    elsif search == "forward_match"
      @post = Post.where("body LIKE?","#{word}%")
    elsif search == "backward_match"
      @post = Post.where("body LIKE?","%#{word}")
    elsif search == "partial_match"
      @post = Post.where("body LIKE?","%#{word}%")
    else
      @post = Post.all
    end
  end

  def create_notification_favorite!(current_user)
    # すでに「いいね」されているか検索
    temp = Notification.where(["visiter_id = ? and visited_id = ? and post_id = ? and action = ? ", current_user.id, user_id, id, 'favorite'])
    # いいねされていない場合のみ、通知レコードを作成
    if temp.blank?
      notification = current_user.active_notifications.new(
      post_id: id,
      visited_id: user_id,
      action: 'favorite'
      )
      # 自分の投稿に対するいいねの場合は、通知済みとする
      if notification.visiter_id == notification.visited_id
        notification.checked = true
      end
      notification.save if notification.valid?
    end
  end

  def create_notification_post_comment!(current_user, post_comment_id)
    # 自分以外にコメントしている人をすべて取得し、全員に通知を送る
    temp_ids = PostComment.select(:user_id).where(post_id: id).where.not(user_id: current_user.id).distinct
    temp_ids.each do |temp_id|
      save_notification_post_comment!(current_user, post_comment_id, temp_id['user_id'])
    end
    # まだ誰もコメントしていない場合は、投稿者に通知を送る
    save_notification_post_comment!(current_user, post_comment_id, user_id) if temp_ids.blank?
  end

  def save_notification_post_comment!(current_user, post_comment_id, visited_id)
    # コメントは複数回することが考えられるため、１つの投稿に複数回通知する
    notification = current_user.active_notifications.new(
      post_id: id,
      post_comment_id: post_comment_id,
      visited_id: visited_id,
      action: 'post_comment'
    )
    # 自分の投稿に対するコメントの場合は、通知済みとする
    if notification.visiter_id == notification.visited_id
      notification.checked = true
    end
    notification.save if notification.valid?
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  def index
    @page = Post.all.page(params[:page]).per(10)
    @posts = Post.all
    @post_comment = PostComment.new
  end

  def show
    @post = Post.find(params[:id])
    @post_comment = PostComment.new
  end


  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to admin_posts_path
  end

  private

  def post_params
    params.require(:post).permit(:body,:image)
  end

end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/views/admin/posts/index.html.erb
<%= stylesheet_link_tag "post", :media => "all" %>
<div class="container">
  <div class="row g-4">
    <div class="col-lg-9 vstack gap-4">
        <div class="mb-3 mt-3">
      <% @posts.each do |post| %>
      <article class="card mt-4 mx-2">
        <div class="card-header border-0 pb-0  bg-white">
          <div class="d-flex align-items-center justify-content-between">
             <div class="d-flex align-items-center">
               <div class="avatar avatar-story me-2">
                 <%= image_tag post.user.get_profile_image(50,50) %>
                </div>
                <div class="nav nav-divider">
                  <h6 class="nav-item card-title mb-0 text-dark text-decoration-none">
                    <%= link_to "#{post.user.name}", admin_user_path(post.user.id), class: "text-dark text-decoration-none" %>
                  </h6>
                  <span class="nav-item small">・<%= post.created_at.strftime('%Y/%m/%d/%H:%M') %></span>
                </div>
              </div>
          </div>
        <div>
        <div class="card-body">
          <p class="h5 mt-2">
            <%= post.body %>
          </p>
          <p class ="text-center mt-3 mb-3">
            <% if post.image.present? %>
            <%= image_tag post.image, size: "300x300" %>
            <% else %>
            <% end %>
          </p>
            <ul class="nav nav-stack py-3 small">
              <li class="nav-item h6">
              <i class="fas fa-trash-alt"></i>
              <%= link_to '消す',admin_post_path(post.id), method: :delete, data: { confirm: '本当に消しますか？' }, class: "text-dark destroy_book_#{post.id}"%>
              </li>
              </li>
              <li class="nav-item h6 ml-3">
                <i class="far fa-comment-dots"></i>
                <%= link_to "#{post.post_comments.count} コメント", admin_post_path(post.id), class: "text-dark" %>
              </li>
            </ul>
          </tr>
      </article>
      <% end %>
  </div>
</div>
<h5 class="d-flex mt-4 justify-content-center ms-sm-auto">
  <%= paginate @page %>
</h5>

app/views/admin/posts/new.html.erb
<h1>Admin::Posts#new</h1>
<p>Find me in app/views/admin/posts/new.html.erb</p>

app/views/admin/posts/show.html.erb
<%= stylesheet_link_tag "post", :media => "all" %>
<div class='container'>
  <div class='row'>
    <div class="col-lg-8 mx-auto">
      <div class="card card-body">
        <img class="card-img rounded">
        <div class="d-flex align-items-center justify-content-between my-3">
          <div class="d-flex align-items-center">
            <div class="avatar avatar-story me-2">
              <img class="avatar-img rounded-circle">
                <%= image_tag @post.user.get_profile_image(70,70) %>
            </div>
            <div>
              <div class="nav nav-divider">
                <h6 class="nav-item card-title mb-0"><%= @post.user.name %></h6>
                <span class="nav-item small"> ・<%= @post.created_at.strftime('%Y/%m/%d/%H:%M') %></span>
              </div>
            </div>
          </div>
        </div>
        <div class="text-center">
          <% if @post.image.present? %>
          <%= image_tag @post.image, size: "400x400" %>
          <% else %>
          <% end %>
        </div>
        <div class="h5 mt-3 mb-3">
          <%= @post.body %>
        </div>
        <ul class="nav nav-stack py-3 small">
          <li class="nav-item h6 ml-3">
            <i class="fas fa-trash-alt"></i>
              <%= link_to '消す',admin_post_path(@post.id), method: :delete, data: { confirm: '本当に消しますか？' }, class: "text-dark destroy_book_#{@post.id}"%>
          </li>
        </ul>
        <% @post.post_comments.each do |post_comment| %>
        <ul class="comment-wrap list-unstyled">
          <div class="d-flex position-relative">
            <div class="avatar avatar-xs">
              <%= image_tag post_comment.user.get_profile_image(50,50) %>
            </div>
            <div class="ms-2">
              <div class="bg-light rounded-start-top-0 p-3 rounded ml-3">
                <div class="d-flex justify-content-between">
                  <h6 class="mb-1">
                    <%= post_comment.user.name %>
                    <%= link_to admin_post_post_comment_path(post_comment.post, post_comment), class: "ml-3 text-dark", method: :delete do %>
                       <i class="fas fa-trash-alt"></i>
                    <% end %>
                  </h6>
                  <small class="ms-2"><%= post_comment.created_at.strftime('%Y/%m/%d/%H:%M') %></small>
                </div>
                <p class="small mb-0"><%= post_comment.comment %></p>
              </div>
            </div>
          </div>
        </ul>
        <% end %>
      </div>
    </div>
  </div>
</div>