config/routes.rb
Rails.application.routes.draw do
  get 'time/index'
  # 会員用
# URL /customers/sign_in ...
devise_for :users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
#ゲストユーザー
devise_scope :user do
  post 'users_guest_sign_in', to: 'public/sessions#guest_sign_in'
end

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  ########### 会員側のルーティング設定 ##########
  scope module: :public do
    root to: "homes#top"
    get '/home/about' => 'homes#about', as: 'about'
    resources :users, only: [:show, :edit, :destroy, :update, :create] do
      resource :follows, only: [:create, :destroy]
      get 'followings' => 'follows#followings', as: 'followings'
      get 'followers' => 'follows#followers', as: 'followers'
    end

    resources :posts, only: [:new, :create, :index, :show, :destroy] do
      resource :favorites, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
    end
    get "search" => "searches#search"
    get 'chat/:id', to: 'chats#show', as: 'chat'
    resources :chats, only: [:create]
    resources :notifications, only: [:index] do
      collection do
        delete 'destroy_all'
      end
    end
    resources :times, only: [:index]
  end

  ########## 管理者側のルーティング設定 ##########
  namespace :admin do
    resources :users, only: [:index, :show, :edit, :destroy, :update]
    resources :posts, only: [:new, :create, :index, :show, :destroy] do
      resources :post_comments, only: [:create, :destroy]
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :follows, class_name: "Follow", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_follows, class_name: "Follow", foreign_key: "followed_id", dependent: :destroy
  has_many :followings, through: :follows, source: :followed
  has_many :followers, through: :reverse_of_follows, source: :follower
  has_many :user_rooms, dependent: :destroy
  has_many :chats, dependent: :destroy
  has_many :active_notifications, class_name: "Notification", foreign_key: "visiter_id", dependent: :destroy
  has_many :passive_notifications, class_name: "Notification", foreign_key: "visited_id", dependent: :destroy
  validates :introduction,presence:true,length:{minimum:1, maximum:300}


  has_one_attached :profile_image

  def get_profile_image(width,height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no-image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  def follow(user_id)
    follows.create(followed_id: user_id)
  end

  def unfollow(user_id)
    follows.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end

  def create_notification_follow!(current_user)
    temp = Notification.where(["visiter_id = ? and visited_id = ? and action = ? ",current_user.id, id, 'follow'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end

  def self.guest
    find_or_create_by!(name: 'guestuser' ,email: 'guest@example.com') do |user|
    user.password = SecureRandom.urlsafe_base64
    user.name = "guestuser"
    end
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  def index
    @page = Post.all.page(params[:page]).per(10)
    @users = User.all
  end

  def show
    @page = Post.all.page(params[:page]).per(10)
    @user = User.find(params[:id])
    @posts = @user.posts
    @post_new = Post.new
  end

  def edit
    @user = User.find(params[:id])
      render :edit
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_user_path(@user.id), notice: "You have updated user successfully."
    else
      render "users/edit"
    end
  end



  private

    def user_params
      params.require(:user).permit(:name, :introduction, :profile_image)
    end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>ユーザー情報編集</h2>
    <%= form_with model: @user, local: true do |f| %>
      <div class="form-group">
        <%= f.label :ユーザー名 %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :トップ画像 %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group" rows="4" cols="40">
        <%= f.label :自己紹介 %>
        <%= f.text_area :introduction , size: "40x15",class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit 'へんしゅう', class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/users/index.html.erb
<h4 class="text-center mt-5">ユーザー一覧</h4><br/>
<div class="container">
  <div class="row">
      <% @users.each do |user| %>
        <table class="table table-hover">
          <tr>
            <td class="text-center", style="width: 20%">
              <%= image_tag user.get_profile_image(50,50) %>
            </td>
            <td class="align-middle h4", style="width: 20%">
              <%= link_to "#{user.name}", admin_user_path(user.id), class: "text-dark text-decoration-none" %>
            </td>
            <td class="align-middle">
              <%= user.introduction %>
            </td>
          </tr>
        </table>
      <% end %>
  </div>
</div>
<h5 class="d-flex mt-4 justify-content-center ms-sm-auto">
  <%= paginate @page %>
</h5>

app/views/admin/users/show.html.erb
<%= stylesheet_link_tag "user", :media => "all" %>
<div class='container'>
  <div class='row'>
    <div class='vstack gap-4'>
      <div class='card'>
        <div class='h-200px rounded-top bg-warning'>
        </div>
        <div class='card-body py-0'>
          <div class='d-sm-flex align-items-start text-sm-start border-bottom'>
            <div class='avatar avatar-xxl mt-n5 mb-3'>
              <img class='avatar-imag rounded-circle border-white border-3'>
                <%= image_tag @user.get_profile_image(120,120) %>
            </div>
            <div class='ms-sm-4'>
              <h1 class='mt-3 mb-0 ml-3 h3'>
                <%= @user.name %>
              </h1>
            </div>
            <div class="ms-sm-auto mt-3 text-center">
              <ul class = "list-inline mb-0 text-sm-start h8">
                <i class="fas fa-child"></i> <%= link_to "フォロー", user_followings_path(@user),class: "text-dark" %>: <%= @user.followings.count %></li>
                <i class="fas fa-users ml-4"></i><%= link_to "フォロワー", user_followers_path(@user),class: "text-dark" %>: <%= @user.followers.count %></li>
                <i class= "ml-2"></i>
              </ul>
            </div>
            <div class = "d-flex mt-4 justify-content-center ms-sm-auto">
                <%= link_to edit_admin_user_path(@user), class: 'btn btn-danger-soft me-2' do %>
                <i class="fas fa-pen"></i>
                <span></span>
                <% end %>
            </div>
          </div>
          <ul class = "list-inline mb-0 sample mt-3 mt-sm-0 h5">
            <h6 class="mt-1">
              <%= simple_format(@user.introduction) %>
            </h6>
          </ul>
        </div>
      </div>
      <% @posts.each do |post| %>
      <article class="card mt-3">
        <div class="card-header border-0 pb-0">
          <div class="d-flex align-items-center justify-content-between">
             <div class="d-flex align-items-center">
               <div class="avatar avatar-story me-2">
                 <%= image_tag post.user.get_profile_image(50,50) %>
                </div>
                <div class="nav nav-divider">
                  <h6 class="nav-item card-title mb-0">
                    <%= @user.name %>
                  </h6>
                  <span class="nav-item small">・<%= post.created_at.strftime('%Y/%m/%d/%H:%M') %></span>
                </div>
              </div>
          </div>
        <div>
        <div class="card-body">
          <p class="h5 mt-2">
            <%= post.body %>
          </p>
          <p class="text-center mt-3 mb-3">
            <% if post.image.present? %>
            <%= image_tag post.image, size: "300x300" %>
            <% else %>
            <% end %>
          </p>
            <ul class="nav nav-stack py-3 small">
              <li class="nav-item h6 ml-3 text-dark">
                <i class="far fa-comment-dots"></i></i>
                <%= link_to "#{post.post_comments.count} コメント", admin_post_path(post.id), class: "text-dark" %>
              </li>
            </ul>
          </tr>
      </article>
      <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<h5 class="d-flex mt-4 justify-content-center ms-sm-auto">
  <%= paginate @page %>
</h5>