config/routes.rb
Rails.application.routes.draw do
  get 'time/index'
  # 会員用
# URL /customers/sign_in ...
devise_for :users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
#ゲストユーザー
devise_scope :user do
  post 'users_guest_sign_in', to: 'public/sessions#guest_sign_in'
end

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  ########### 会員側のルーティング設定 ##########
  scope module: :public do
    root to: "homes#top"
    get '/home/about' => 'homes#about', as: 'about'
    resources :users, only: [:show, :edit, :destroy, :update, :create] do
      resource :follows, only: [:create, :destroy]
      get 'followings' => 'follows#followings', as: 'followings'
      get 'followers' => 'follows#followers', as: 'followers'
    end

    resources :posts, only: [:new, :create, :index, :show, :destroy] do
      resource :favorites, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
    end
    get "search" => "searches#search"
    get 'chat/:id', to: 'chats#show', as: 'chat'
    resources :chats, only: [:create]
    resources :notifications, only: [:index] do
      collection do
        delete 'destroy_all'
      end
    end
    resources :times, only: [:index]
  end

  ########## 管理者側のルーティング設定 ##########
  namespace :admin do
    resources :users, only: [:index, :show, :edit, :destroy, :update]
    resources :posts, only: [:new, :create, :index, :show, :destroy] do
      resources :post_comments, only: [:create, :destroy]
    end
  end
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
      <title>はつね（子供向け）</title>
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>
      <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
      <%= stylesheet_link_tag "application", :media => "all" %>
      <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>
    <body class="d-flex flex-column vh-100 bg-light">
      <header class="shadow-none bg-white">
        <nav class="navbar navbar-expand-lg navbar-light">
          <div class="container">
            <a class= "navbar-brand p-3"><%= link_to image_tag("logo.png"),root_path, class: 'icon' %></a>
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <% if user_signed_in? %>
              <div class="search_form">
                <%= form_with url: search_path, local: true, method: :get do |f| %>
                <%= f.text_field :word %>
                <%= f.select :range, options_for_select([['ユーザー'], ['投稿']]) %>
                <%= f.select :search, options_for_select([["部分一致","partial_match"],["完全一致","perfect_match"], ["前方一致","forward_match"],  ["後方一致","backword_match"]]) %>
                <%= f.submit "検索", class: "btn btn-primary" %>
                <% end %>
              </div>
              <% end %>
              <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav ml-auto h5">
                  <% if user_signed_in? %>
                    <li class="nav-item">
                      <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-dark' do %>
                      <i class="fas fa-sign-out-alt"></i>ログアウト
                      <% end %>
                    </li>
                    <li class="nav-item h5">
                      <%= link_to posts_path, class: 'nav-link text-dark' do %>
                      <i class="fas fa-dove"></i></i>つぶやき
                      <% end %>
                    </li>
                    <li class="nav-itemh5">
                      <%= link_to user_path(current_user.id), class: 'nav-link text-dark' do %>
                      <i class="fas fa-user-circle"></i>マイページ
                      <% end %>
                    </li>
                    <% if unchecked_notifications.any? %>
                     <i class="fa fa-circle" style="color: gold;"></i>
                    <% end %>
                    <li class="nav-item h5">
                      <%= link_to notifications_path, class: 'nav-link text-dark' do%>
                      <i class="fas fa-bell"></i>つうち
                      <% end %>
                    </li>
                  <% elsif admin_signed_in? %>
                    <li class="nav-item">
                      <%= link_to destroy_admin_session_path, method: :delete, class: 'nav-link text-dark' do %>
                      <i class="fas fa-sign-out-alt"></i>ログアウト
                      <% end %>
                    </li>
                    <li class="nav-item h5">
                      <%= link_to admin_posts_path, class: 'nav-link text-dark' do %>
                      <i class="fas fa-dove"></i></i>つぶやき
                      <% end %>
                    </li>
                     <li class="nav-item h5">
                      <%= link_to admin_users_path, class: 'nav-link text-dark' do %>
                      <i class="fas fa-dove"></i></i>ユーザー
                      <% end %>
                    </li>
                    <li class="nav-item h5">
                      <%= link_to about_path, class: 'nav-link text-dark' do %>
                      <i class="fas fa-egg"></i>はつねについて
                      <% end %>
                    </li>
                  <% else %>
                    <li class="nav-item h5">
                      <%= link_to new_user_registration_path, class: 'nav-link text-dark' do %>
                      <i class="fas fa-user-plus"></i>とうろく
                      <% end %>
                    </li>
                    <li class="nav-item h5">
                      <%= link_to new_user_session_path, class: 'nav-link text-dark' do %>
                      <i class="fas fa-sign-in-alt"></i>ログイン
                      <% end %>
                    </li>
                    <li class="nav-item h5">
                      <%= link_to about_path, class: 'nav-link text-dark' do %>
                      <i class="fas fa-egg"></i>はつねについて
                      <% end %>
                    </li>
                  <% end %>
                </ul>
              </div>
          </div>
        </nav>
      </header>
      <main>
        <%= yield %>
      </main>
      <footer class="text-black-50 pb-4">
        <div class="container">
          <div class="row">
            <div class="col-md-4">
              <p>© Hatune, Inc</p>
            </div>
            <div class="col-md-8">
              <h6 class="text-black-50 mt-2 mb-3 ml-4">リンク</h6>
              <ul class="p-0 list-unstyled text-left">
                <li>
                  <%= link_to "管理者はこちら", admin_session_path, class: 'text-black-50'  %>
                </li>
                <li>
                  <a>プライバシーポリシー</a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </footer>
    </header>
  </body>
</html>